---
name: CI with maven
on:
  push:
    branches:
      - main
jobs:
  build:
    name: 'maven'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: maven build
        run: mvn package
        
