---
name: CI with maven

run-name: build maven

on:
  push:
    branches:
      - main
jobs:
  build:
    name: 'maven'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: setup java 17
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: '17'
      - name: maven build
        run: mvn package
        
